# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('artist', models.CharField(max_length=128)),
                ('album', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=128)),
                ('mime', models.CharField(max_length=32)),
            ],
        ),
    ]
